ScanariumError: Turn default parameters to dictionary
When parameters are set, they are a dictionary. So the default should
be an empty dictionary, not an empty list.